import '../css/normalize.css';
import {
  create,
  sqrtDependencies,
  evaluateDependencies,
  invDependencies,
  sinDependencies,
  cosDependencies,
  tanDependencies,
  addDependencies,
  subtractDependencies,
  multiplyDependencies,
  divideDependencies,
  powDependencies,
  factorialDependencies,
  logDependencies,
  piDependencies,
  eDependencies,
  cbrtDependencies,
  sinhDependencies,
  coshDependencies,
  tanhDependencies,
  randomDependencies,
  log10Dependencies,
  asinDependencies,
  acosDependencies,
  atanDependencies,
  asinhDependencies,
  acoshDependencies,
  atanhDependencies,
  formatDependencies,
  unaryMinusDependencies,
  nthRootDependencies,
} from 'mathjs';

const { evaluate } = create({
  sqrtDependencies,
  evaluateDependencies,
  invDependencies,
  sinDependencies,
  cosDependencies,
  tanDependencies,
  addDependencies,
  subtractDependencies,
  multiplyDependencies,
  divideDependencies,
  powDependencies,
  factorialDependencies,
  logDependencies,
  piDependencies,
  eDependencies,
  cbrtDependencies,
  sinhDependencies,
  coshDependencies,
  tanhDependencies,
  randomDependencies,
  log10Dependencies,
  asinDependencies,
  acosDependencies,
  atanDependencies,
  asinhDependencies,
  acoshDependencies,
  atanhDependencies,
  unaryMinusDependencies,
  nthRootDependencies,
});

const { format } = create({ formatDependencies });

export { evaluate, format };
